---
title: "Spatial point pattern analysis"
author: "Eleanor Jackson"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  html_document: 
    keep_md: yes
    theme: lumen
    highlight: pygments
---

```{r, warning=FALSE, message=FALSE}
rm(list = ls())
library("tidyverse"); theme_set(theme_bw(base_size=10))
library("rdist")
library("parallel")
library("lme4")
library("ggeffects")
library("spatstat")
library("knitr"); opts_chunk$set(tidy.opts=list(width.cutoff=50), 
	tidy=FALSE, cache.lazy = FALSE,cache = TRUE)

```

```{r, warning=FALSE, results="hide"}
load("../data/raw/bci.tree/bci.tree8.rdata")
load("../data/raw/bci.spptable.rdata")
trapDat <- read.csv("../output/tables/proportionAbscisedPerTrap.csv") 
RST <- read.csv("../output/tables/R50.csv")

bci.tree8$year <- "2015"
trapDat <- subset(trapDat, trapDat$year == "2015" & trapDat$SP6=="cordbi")
bci8 <- left_join(bci.tree8, bci.spptable, by = "sp")
bci8 <- left_join(bci8, RST, by = "sp")
bci8 <- subset(bci8, bci8$status == "A" & bci8$dbh > bci8$R50 & bci8$sp =="cordbi")

trapDat$trap <- paste("trap", trapDat$trap, sep="_")
bci8$treeID <- paste("tree", bci8$treeID, sep="_")

bci8 %>%
	select(treeID, gx, gy, dbh) %>%
	rename(X = gx, Y = gy, ID = treeID) %>%
	mutate(type = "tree", proportion_abscised = NA, sum_parts = NA) -> treeDat

trapDat %>%
	select(trap, X, Y, proportion_abscised, sum_parts) %>%
	rename(ID = trap) %>%
	mutate(type = "trap", dbh = NA) -> trapDat

rbind(trapDat, treeDat) -> dat

all_pp <- ppp(dat[,"X"],dat[,"Y"],owin(c(0,1000),c(0,500)), marks=dat$type)
unitname(all_pp) <- c("meter","meter")

###############################

dat.t <- subset(dat, type=="tree")
tree_pp <- ppp(dat.t[,"X"],dat.t[,"Y"],owin(c(0,1000),c(0,500)), marks=dat.t$dbh)
unitname(tree_pp) <- c("meter","meter")
plot(tree_pp)

K2 <- density(tree_pp, weights=tree_pp$marks) 
plot(K2, main="Cordia bicolor, 2015", las=1,legend=FALSE)
contour(K2, add=TRUE, legend=FALSE)
plot.ppp(tree_pp, add=TRUE, maxsize=15, legend=TRUE)

plot.ppp(tree_pp, main="Cordia bicolor, 2015", maxsize=15, legend=TRUE)
plot(K2, add=TRUE, las=1,legend=FALSE)
contour(K2, add=TRUE, legend=FALSE)
plot.ppp(tree_pp, add=TRUE, maxsize=15, legend=FALSE, cols="white")

density(tree_pp, weights=tree_pp$marks, at="points")

library(raster)
library(maptools)

K2.r <- raster(K2)
plot(K2.r)  
xyFromCell(K2.r, which.max(K2.r))

subset(dat, type=="trap") %>% dplyr::select(X, Y) -> trap.points

rasValue<- extract(K2.r, trap.points)
combinePointValue<-cbind(trap.points,rasValue)

left_join(combinePointValue, trapDat, by=c("X", "Y")) -> df

ggplot(subset(df, sum_parts>1)) +
	geom_point(aes(x=rasValue, y=proportion_abscised))

m1 <- ppm(tree_pp ~ polynom(x,y,2))
```