---
title: "Compare binomial models"
author: "Eleanor Jackson"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  github_document:
    keep_html: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.path="figures/29_binom-models-compare/")
```

```{r, warning=FALSE, message=FALSE}
library("tidyverse")
library("brms")
library("patchwork")
library("broom.mixed")
library("modelr")
```

```{r}
bbinom <-
  readRDS(here::here("output", "models", "pheno-repro-adjust",
                     "full_conn_binom_nseeds.rds"))

bbinom_interact <-
  readRDS(here::here("output", "models", "pheno-repro-adjust",
                     "full_conn_binom_nseeds_interact.rds"))

bbinom_interact_abund <-
  readRDS(here::here("output", "models", "pheno-repro-adjust",
                     "full_conn_binom_nseeds_abund.rds"))
```

```{r loo-compare}
comp <- 
  loo_compare(bbinom,
              bbinom_interact,
              bbinom_interact_abund)

print(comp, digits = 3)

comp %>% 
  data.frame() %>% 
  rownames_to_column(var = "model_name") %>% 
  ggplot(aes(x    = model_name, elpd_diff, 
             y    = elpd_diff, 
             ymin = elpd_diff - se_diff, 
             ymax = elpd_diff + se_diff)) +
  geom_pointrange(shape = 21, fill = "white") +
  coord_flip() +
  geom_hline(yintercept = 0, colour = "blue", linetype = 2) +
  labs(x = NULL, y = "difference from model with the largest ELPD", 
       title = "expected log predictive density (ELPD)") 

```

```{r}
my_coef_tab <-
  tibble(fit = list(bbinom,
                 bbinom_interact,
                 bbinom_interact_abund),
         model = c("bbinom",
                 "bbinom_interact",
                 "bbinom_interact_abund")) %>%
  mutate(tidy = purrr::map(
    fit,
    tidy,
    effects = "fixed",
    robust = TRUE
  )) %>%
  unnest(tidy)
```

```{r estimate-compare, fig.height=8, fig.width=5, warning=FALSE}

my_coef_tab %>% 
  mutate(term = as.factor(term)) %>% 
  ggplot(aes(x = term, y = estimate, ymin = conf.low, ymax = conf.high)) +
  geom_pointrange(shape = 21, fill = "white") +
  labs(x = "Parameters",
       y = "Estimate ± CI [95%]") +
  geom_hline(yintercept = 0,  color = "blue") +
  coord_flip() +
  theme_bw() +
  facet_wrap(~model, ncol = 1)

```

No major differences in parameter estimates between models

```{r}
all_plots <- conditional_effects(bbinom_interact_abund,
                    plot = TRUE)
wrap_plots(
  plot(all_plots, plot = FALSE)[[1]],
  plot(all_plots, plot = FALSE)[[2]],
  plot(all_plots, plot = FALSE)[[3]],
  plot(all_plots, plot = FALSE)[[4]],
  plot(all_plots, plot = FALSE)[[5]]
) &
  coord_cartesian(ylim = c(0,1))

wrap_plots(
  plot(all_plots, plot = FALSE)[[6]],
  plot(all_plots, plot = FALSE)[[7]],
  plot(all_plots, plot = FALSE)[[8]] 
) +
  plot_layout(guides = "collect") &
  coord_cartesian(ylim = c(0,1)) &
  theme(legend.position = "top")


wrap_plots(
  plot(all_plots, plot = FALSE)[[9]],
  plot(all_plots, plot = FALSE)[[10]],
  plot(all_plots, plot = FALSE)[[11]] 
)+
  plot_layout(guides = "collect") &
  coord_cartesian(ylim = c(0,1)) &
  theme(legend.position = "top")

```

Rare species drop less fruit prematurely, but
no evidence that species abundance explains effect of neighbourhood density on 
seed abscission.

```{r}
draws <- as_draws_df(bbinom_interact_abund)

draws %>%
  transmute(
    abund_effect_on_RC_vs_RH =
      `b_conn_RC_sc:log_median_abundance_sc` -
      `b_conn_RH_sc:log_median_abundance_sc`
  ) %>%
  summarise(
    mean = mean(abund_effect_on_RC_vs_RH),
    sd = sd(abund_effect_on_RC_vs_RH),
    q025 = quantile(abund_effect_on_RC_vs_RH, 0.025),
    q50  = quantile(abund_effect_on_RC_vs_RH, 0.5),
    q975 = quantile(abund_effect_on_RC_vs_RH, 0.975),
    p_gt_0 = mean(abund_effect_on_RC_vs_RH > 0),
    p_lt_0 = mean(abund_effect_on_RC_vs_RH < 0)
  )
```
```{r}
# there is one abundance value per species
species_abund <- bbinom_interact_abund$data %>%
  distinct(sp4, log_median_abundance_sc)

# extract species random slopes for RC and RH
sp_re <- draws %>%
  select(.draw, matches("^r_sp4\\[")) %>%
  pivot_longer(
    cols = -.draw,
    names_to = "param",
    values_to = "value"
  ) %>%
  filter(str_detect(param, ",conn_RC_sc\\]$|,conn_RH_sc\\]$")) %>%
  mutate(
    sp4 = str_match(param, "^r_sp4\\[(.*?),")[, 2],
    term = str_match(param, ",(conn_RC_sc|conn_RH_sc)\\]$")[, 2]
  ) %>%
  select(.draw, sp4, term, value) %>%
  pivot_wider(names_from = term, values_from = value)

# extract the fixed effects for RC and RH
fixef_rc_rh <- draws %>%
  mutate(
    .draw,
    b_RC = .data[["b_conn_RC_sc"]],
    b_RH = .data[["b_conn_RH_sc"]],
    b_RC_seed = .data[["b_conn_RC_sc:log_total_seeds_sc"]],
    b_RH_seed = .data[["b_conn_RH_sc:log_total_seeds_sc"]],
    b_RC_abund = .data[["b_conn_RC_sc:log_median_abundance_sc"]],
    b_RH_abund = .data[["b_conn_RH_sc:log_median_abundance_sc"]],
    .keep = "none"
  )

# fix log total seeds at zero (the mean)
L0 <- 0

# compute the RC-RH contrast per draw
species_rc_rh_draws <- fixef_rc_rh %>%
  left_join(sp_re, by = ".draw") %>%
  left_join(species_abund, by = "sp4") %>%
  mutate(
    rc_rh_contrast =
      (b_RC - b_RH) +
      (b_RC_seed - b_RH_seed) * L0 +
      (b_RC_abund - b_RH_abund) * log_median_abundance_sc +
      (conn_RC_sc - conn_RH_sc)
  ) %>%
  select(.draw, sp4, log_median_abundance_sc, rc_rh_contrast)

# summarise draws
species_rc_rh_summary <- species_rc_rh_draws %>%
  group_by(sp4) %>%
  summarise(
    mean = mean(rc_rh_contrast),
    sd = sd(rc_rh_contrast),
    q025 = quantile(rc_rh_contrast, 0.025),
    q50  = quantile(rc_rh_contrast, 0.50),
    q975 = quantile(rc_rh_contrast, 0.975),
    p_gt_0 = mean(rc_rh_contrast > 0),
    p_lt_0 = mean(rc_rh_contrast < 0),
    .groups = "drop"
  )

species_rc_rh_summary
```


```{r fig.height=8, fig.width=4}
species_rc_rh_draws %>%
  ggplot(aes(y = reorder(sp4, rc_rh_contrast), x = rc_rh_contrast)) +
  ggdist::stat_gradientinterval(.width = 0.95, fill = "forestgreen",
                                stroke = 0.5, linewidth = 0.5,
                                shape = 21, fatten_point = 0.7,
                                point_fill = "white") +
  labs(x = "Stabilising CNDD effect", y = "") +
  coord_cartesian(xlim = c(-2.5, 5)) +
  geom_vline(xintercept = 0, linetype = 1, colour = "blue",linewidth = 0.25) 
```

Stabilizing CNDD = CNDD - HNDD 

On the logit scale

```{r}
species_rc_rh_draws %>%
  ggplot(aes(y = rc_rh_contrast, x = log_median_abundance_sc, group = sp4)) +
  ggdist::stat_gradientinterval(.width = 0.95, fill = "forestgreen",
                                stroke = 0.5, linewidth = 0.5,
                                shape = 21, fatten_point = 0.7,
                                point_fill = "white",
                                orientation = "vertical") +
  labs(y = "Stabilising CNDD effect", x = "Species abundance") +
  coord_cartesian(ylim = c(-2.5, 5))
```

# Check correlations between density estimates

```{r}
bbinom_interact_abund$data %>%
  ggplot(aes(x = conn_RC_sc, conn_RH_sc)) +
  geom_point() +
  geom_smooth(method = "lm") +
  
  bbinom_interact_abund$data %>%
  ggplot(aes(x = conn_RC_sc, conn_NRC_sc)) +
  geom_point() +
  geom_smooth(method = "lm") +
  
  bbinom_interact_abund$data %>%
  ggplot(aes(x = conn_RH_sc, conn_NRC_sc)) +
  geom_point() +
  geom_smooth(method = "lm") 


cor.test(bbinom_interact_abund$data$conn_RC_sc,
         bbinom_interact_abund$data$conn_RH_sc)

cor.test(bbinom_interact_abund$data$conn_RC_sc,
         bbinom_interact_abund$data$conn_NRC_sc)

cor.test(bbinom_interact_abund$data$conn_RH_sc,
         bbinom_interact_abund$data$conn_NRC_sc)
```

